function PicoSetup(hApp)

    valRange = hApp.DropDownRange.Value;

    [status.chA] = invoke(hApp.hPicoScope, 'ps5000aSetChannel', ...
                          hApp.infoEnum.enPS5000AChannel.PS5000A_CHANNEL_A, ...
                          PicoConstants.ENABLE, ...
                          hApp.infoEnum.enPS5000ACoupling.PS5000A_AC, ...
                          valRange, ...
                          0.0);
    
    [status.chB] = invoke(hApp.hPicoScope, 'ps5000aSetChannel', ...
                          hApp.infoEnum.enPS5000AChannel.PS5000A_CHANNEL_B, ...
                          PicoConstants.DISABLE, ...
                          hApp.infoEnum.enPS5000ACoupling.PS5000A_AC, ...
                          valRange, ...
                          0.0);
    
    [status.chC] = invoke(hApp.hPicoScope, 'ps5000aSetChannel', ...
                          hApp.infoEnum.enPS5000AChannel.PS5000A_CHANNEL_C, ...
                          PicoConstants.DISABLE, ...
                          hApp.infoEnum.enPS5000ACoupling.PS5000A_AC, ...
                          valRange, ...
                          0.0);
    
    [status.chD] = invoke(hApp.hPicoScope, 'ps5000aSetChannel', ...
                          hApp.infoEnum.enPS5000AChannel.PS5000A_CHANNEL_D, ...
                          PicoConstants.DISABLE, ...
                          hApp.infoEnum.enPS5000ACoupling.PS5000A_AC, ...
                          valRange, ...
                          0.0);
    
    % Set device resolution
    % Only using one channel the maximum depth is 16 bit
    invoke(hApp.hPicoScope, ...
          'ps5000aSetDeviceResolution',...
           16);


    timebase = round(1/hApp.EditFieldFs.Value * 62.5 + 3);
    
    % Set timebase to 28 which leads to a sample rate around 2.5 MHz
    [~, tNs, ~] = invoke(hApp.hPicoScope, ...
                         'ps5000aGetTimebase2',...
                         timebase, ...
                         0);
    hApp.EditFieldFs.Value = 1e3/double(tNs); 
    set(hApp.hPicoScope, 'timebase', timebase);
    
    % Setup trigger
    triggerGroupObj = get(hApp.hPicoScope, 'Trigger');
    triggerGroupObj = triggerGroupObj(1);
    % Disable auto trigger
    set(triggerGroupObj, 'autoTriggerMs', 0);
    
    invoke(triggerGroupObj, 'setSimpleTrigger',...
           hApp.infoEnum.enPS5000AChannel.PS5000A_EXTERNAL, ...
           1000,... % 1000 mv threshold
           hApp.infoEnum.enPS5000AThresholdDirection.PS5000A_RISING);
    
    set(hApp.hPicoScope, 'numPreTriggerSamples', hApp.EditFieldPre.Value);
    set(hApp.hPicoScope, 'numPostTriggerSamples', hApp.EditFieldPost.Value);

    hApp.hBlockObj = get(hApp.hPicoScope, 'Block');
    hApp.hBlockObj = hApp.hBlockObj(1);

end